import pipeline.exceptions as exc

from pipeline.scanning.base import BaseScanner
from pipeline.common.tools import CommandTools
from pipeline.common.gitlab import PredefinedVariables

class UnitTests(BaseScanner):
    def run_analysis(self):
        result = CommandTools.run_command(
            "mvn verify",
            workdir=PredefinedVariables.CI_PROJECT_DIR
        )
        self.logger.info(f"{result.stdout}\n\n{result.stderr}")
        return result

    def execute(self):
        self.printer.info("Ejecutando pruebas unitarias...")
        result = self.run_analysis()
        if result.returncode != 0:
            raise exc.ExitError(
                user_message="Las pruebas unitarias han fallado.",
                log_message="Unit tests failed."
            )
        self.printer.success("Las pruebas unitarias se han completado con éxito.")
    
    def make_report(self):
        # The report is already generated by the maven-surefire-plugin
        pass